### PR TITLE
Feature/brbdcf 1142 shared hostpool

### PR DESCRIPTION
**Pull request by stebenoist**
## Description of the change

**New host pool property:**
- An allocations slice prop has been added to describe the related host pool allocations.
An allocation is defined by a node name, an instance and is related deploymentID.

**New Tosca Compute property:**
- A "**shareable**" Tosca property has been added to the compute

When Tosca host capabilities resources properties (**host.num_cpus, host.mem_size, host.disk_size**) are specified in the deployed application and in host pool labels too, these values are respectively **decreased** and **increased** when host is allocated and released for the application.

The shareable host pool status is allocated as long as it has at least one allocation.
The shareable host pool status is free when it has no allocations.

### Create a hostpool with the following template:
`hosts:
- name: host1
  connection:
    user: ubuntu
    private_key: ***********************
    host: **********
    port: 22
  labels:
    environment: dev
    host.disk_size: 50 GB
    host.mem_size: 8GB
    host.num_cpus: "8"
    os.architecture: x86_64
    os.distribution: ubuntu
    os.type: linux
    os.version: "16.04"`

### Apply this config:
`$ ./yorc hp apply host_pool.yaml`

### Deploy a 2 compute-instances application with a simple component as Python
[https://github.com/ystia/yorc-a4c-plugin/tree/develop/tosca-samples/org/ystia/yorc/samples/python](url)

### Specify the following host capabilities properties:
- host.num_cpus = 4
- host.mem_size = 4 GB
- host.disk_size = 20 GB

### Check the deployment is correctly done
Check the hostpool CLI informations: 
`$ ./yorc hp list`
- 2 allocations must be set with nodename, instance and deployment ID
- host.num_cpus = 0
- host.mem_size = 0 B
- host.disk_size = 0 B

### Undeploy the application:
- Check the undeployment is correctly done
- Check the host pool informations 
`$ ./yorc hp list`
- no allocations
- host.num_cpus = 8
- host.mem_size = 8 GB
- host.disk_size = 40 GB

### CODE REVIEW

**Comment by laurentganne** [comment]
For the verification step, we have to patch the alien4cloud yorc plugin to have the new property shareable appear in the Compute node, right ?

**Comment by stebenoist** [comment]
Yes, that's correct. I add a PR on the plugin side.

**Comment by stebenoist** [comment]
Thanks, I fix it.

**Comment by laurentganne** [comment]
Previous issue on 'yorc hp apply' fixed.
Just 2 test cases causing issues to allocated resources computation:
  * update the hosts pool config when there are allocated hosts
    The user runs 'yorc hp apply host_pool.yaml' then deployed an application
    The user then runs again  'yorc hp apply host_pool.yaml'
    => resources counters are resetted to the max value, and allocation messages are lost
    When the user undeploys the application, resources are incremented and so go above the capacity of the host
  * Do one deployment containing applications deployed on several compute nodes
    Allocated resources are less than expected

**Comment by stebenoist** [comment]
I've just fixed the 2nd issue. Need some work to fix the first one.

**Pull request merged**
