### PR TITLE
[Backport 4.0] Fix Bootstrap on Centos 7 on GCP fails

### LINKED ISSUE #649: Bootstrap on Centos 7 on GCP fails
# Bug Report

## Actual behavior

Bootstrap fails to install `pip` using `easy_install` see ystia/forge#131 for more details

## Additional environment details (infrastructure implied: AWS, OpenStack, etc.)

GCP centos 7

## Output of `yorc version`

4.0.1

### PR DESCRIPTION
**Pull request by loicalbertin**
# Pull Request description

### What I did

Update bootstrap tosca types with Forge PR ystia/forge#132

### How to verify it

Bootstrap on with centos7 GCP

### Description for the changelog

* Bootstrap on Centos 7 on GCP fails ([GH-649](https://github.com/ystia/yorc/issues/649))

## Applicable Issues

Fixes #649 

## Backports

Backport of #650

### CODE REVIEW

**Comment by laurentganne** [comment]
Seeing this error during the bootstrap, will have a look:

```
    The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.

    The error appears to have been in '/home/yorcuser/bootstrap/work/deployments/testtmp/overlay/org.ystia.ansible.linux.ansible/2.2.0-SNAPSHOT/playbooks/create.yml': line 59, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


        - name: install Ansible using Pip
          ^ here

```

**Comment by loicalbertin** [comment]
Also note that I have to document that epel repositories on Centos are now required for bootstrap Yorc

**Comment by laurentganne** [comment]
The issue should be in org/ystia/ansible/linux/ansible/playbooks/create.yml
at :
```yaml
extra_args: "{{ '--extra-index-url {}'.format(ANSIBLE_EXTRA_PACKAGE_REPOSITORY) if ANSIBLE_EXTRA_PACKAGE_REPOSITORY != ''}}"
```
Adding a else seems to fix the issue,
to have this defintion for extra_args:
```yaml
extra_args: "{{ '--extra-index-url {}'.format(ANSIBLE_EXTRA_PACKAGE_REPOSITORY) if ANSIBLE_EXTRA_PACKAGE_REPOSITORY != ''  else ''}}"
```

**Comment by loicalbertin** [comment]
Ok will add this but should be somehow dependent on a 3thd party lib as I tested it and it worked for me

**Comment by loicalbertin** [comment]
Could you please port this change to the forge too?
Thanks

**Comment by laurentganne** [comment]
> Ok will add this but should be somehow dependent on a 3thd party lib as I tested it and it worked for me

I just pushed the change. Yes, I didn't find what in my setup produced a different behavior. This is a CentOS 7.8.2003 GCP VM created several months ago to perform bootstraps.

**Comment by laurentganne** [comment]
> Could you please port this change to the forge too?
> Thanks

yes, will do

**Pull request merged**
